// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeasonalRNDServer;

namespace SeasonalRNDServer.Migrations
{
    [DbContext(typeof(SeasonalDbContext))]
    partial class SeasonalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeasonalRNDServer.Models.Seasonal", b =>
                {
                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<string>("events")
                        .HasColumnType("text");

                    b.Property<string>("historicalData")
                        .HasColumnType("text");

                    b.Property<string>("predictedData")
                        .HasColumnType("text");

                    b.HasKey("date");

                    b.ToTable("events");
                });
#pragma warning restore 612, 618
        }
    }
}
